---
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
version: "0.2.2"
slug: cybroscgiserver
name: CybroScgiServer
description:
  SCGI serer to communicate to PLCs from Cybrotech / Robotina
  # yamllint disable-line rule:line-length
url: https://github.com/killer0071234/hassio-cybroscgiserver
codenotary: killer007@gmx.at
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  configuration_file: /config/cybroscgiserver_config.ini
  autodetect_address: 192.168.1.255
  request_period_s: 5
  valid_period_s: 10
  cleanup_period_s: 60
schema:
  configuration_file: str
  autodetect_address: str
  request_period_s: int(0,60)
  valid_period_s: int(0,60)
  cleanup_period_s: int(0,300)
  verbose_level: list(DEBUG|INFO|WARNING|ERROR|CRITICAL)?
ports:
  4000/tcp: 4000
  8442/udp: 8442
map:
  - homeassistant_config:rw
  - addon_config:rw
host_network: true
image: ghcr.io/killer0071234/cybroscgiserver/{arch}
