version: 0.2.4
slug: cybroscgiserver
name: CybroScgiServer
description: SCGI serer to communicate to PLCs from Cybrotech / Robotina
url: https://github.com/killer0071234/hassio-cybroscgiserver
codenotary: killer007@gmx.at
init: false
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
options:
  configuration_file: /config/cybroscgiserver_config.ini
schema:
  configuration_file: str
  autodetect_address: str?
  push_enabled: bool?
  verbose_level: list(DEBUG|INFO|WARNING|ERROR|CRITICAL)?
ports:
  4000/tcp: 4000
  8442/udp: 8442
map:
- homeassistant_config:rw
- addon_config:rw
host_network: true
image: ghcr.io/killer0071234/cybroscgiserver/{arch}
