---
version: 0.1.2
slug: cybroscgiserver
name: CybroScgiServer
description: SCGI serer to communicate to PLCs from Cybrotech / Robotina
url: https://github.com/killer0071234/hassio-cybroscgiserver
codenotary: killer007@gmx.at
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  configuration_file: /config/cybroscgiserver_config.ini
schema:
  configuration_file: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
ports:
  80/tcp: null
  4000/tcp: 4000
  8442/udp: 8442
ports_description:
  80/tcp: SCGI Web interface (with nginx as proxy)
  4000/tcp: SCGI port (Used for Integrations. eg. ha-hiq)
  8442/udp: Abus push port
map:
  - config:rw
