---
name: Repository Updater
# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types: ["update"]
jobs:
  workflows:
    name: Publish add-on update
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Run Repository Updater
        uses: killer0071234/repository-updater@git-user-git-email
        with:
          addon: ${{ github.event.client_payload.addon }}
          repository: ${{ github.repository }}
          token: ${{ secrets.UPDATER_TOKEN }}
